export default [
  {
    name: "John Doe",
    age: 45,
    gender: "Male",
    dateOfBirth: new Date("1979-03-25"),
    weight: 80,
    height: 175,
    maritalStatus: "Married",
    maillingAddress: "john@gmail.com",
    roomNumber: "A101",
    religion: "Christian",
    workPhone: "123-456-7890",
    personalPhone: "987-654-3210",
    attendingPhysician: {
      name: "Dr. Smith",
      date: new Date("2025-04-01"),
    },
    followUpNotes: 
      {
        note: "Patient has recovered well from the surgery.",
        date: new Date("2025-04-02"),
      },
    emergencyContact: {
      contactName: "Jane Doe",
      phoneNumber: "555-123-4567",
      relationship: "Spouse",
    },
    levelOfConsciousness: "Alert",
    painAssessment: {
      onset: "Sudden",
      provocation: "Movement",
      quality: "Sharp",
      radiation: "None",
      severity: "Moderate",
      time: "Morning",
    },
    allergies: [
      {
        date: new Date("2024-05-10"),
        substance: "Penicillin",
        symptoms: "Rash",
      },
      {
        date: new Date("2024-05-10"),
        substance: "Penicillin",
        symptoms: "Idk",
      },
    ],
    medications: [
      {
        date: new Date("2025-03-28"),
        medication: "Ibuprofen",
        strength: "200mg",
      },
    ],
    pastMedicalHistory: "Hypertension",
    vitalSignCheck: {
      heartRate: "72 bpm",
      bloodPressure: "120/80 mmHg",
      oxygenSaturation: "98%",
      temperature: "37.0°C",
      respiratoryRate: "18 breaths/min",
      gcs: "15",
      checkedBy: {
        name: "Dr. Johnson",
        dateTime: "2025-04-01 10:00 AM",
      },
    },
    immunizations: [
      {
        date: new Date("2024-01-15"),
        type: "Flu Shot",
        site: "Left Arm",
      },
    ],
    nutrition: {
      hasFoodAllergies: "Yes",
      specificDiet: "Low Sodium",
      mealsPerDay: "3",
      chewingOrSwallowingDifficulty: "No",
      fruitVegConsumption: "Daily",
      enoughWaterDaily: "Yes",
      appetiteIssues: "No",
      consumesSugaryProcessedFoods: "No",
    },
    chiefComplaint: "Chest pain",
    signsAndSymptoms: "Dizziness, shortness of breath",
    caseType: "Medical",
    circulationPulse: "Strong",
    breathing: "Present",
    breathingSound: "Clear",
    breathingQuality: "Normal",
    oxygen: {
      required: "No",
      details: [],
    },
    adjuncts: {
      intubated: "No",
      avFistula: "No",
      colostomyBag: "No",
      paceMaker: "No",
    },
    traumaBurnAssessment: {
      wholeHeadNeck: "No",
      entireRightArm: "No",
      entireLeftArm: "No",
      entireTrunk: "No",
      groin: "No",
      entireRightLeg: "No",
      entireLeftLeg: "No",
    },
    treatmentPlan: "Monitor vitals, manage pain",
    recoveryPlan: "Follow-up after 2 weeks",
    interventions: "Pain medication",
    evaluation: "Improvement noted in pain levels",
    labResults: [
      {
        typeOfTest: "Blood Test",
        collectionDate: new Date("2025-03-30"),
        provider: "Dr. Lee",
        result: "Normal"
      },
    ],
    imagingResults: [
      {
        typeOfImaging: "X-Ray",
        dateOfExam: new Date("2025-03-29"),
        provider: "Dr. Wang",
        result: "Fractured Bone in Left Arm"
      },
    ],
    endorsements: [
      {
        answer: "Approved",
        endorsedBy: "Dr. Smith",
        endorsedAt: "2025-04-01 11:00 AM",
        receivedBy: "Nurse Jane",
        receivedAt: "2025-04-01 11:30 AM",
      },
      {
        answer: "Test File",
        endorsedBy: "Dr. Claridad",
        endorsedAt: "2025-04-01 11:00 AM",
        receivedBy: "Nurse Jane",
        receivedAt: "2025-04-01 11:30 AM",
      },
    ],
  },
  {
    name: "Alice Adams",
    age: 30,
    gender: "Female",
    dateOfBirth: new Date("1994-07-12"),
    weight: 65,
    height: 160,
    maritalStatus: "Single",
    maillingAddress: "alice@gmail.com",
    roomNumber: "B202",
    religion: "Muslim",
    workPhone: "321-654-9870",
    personalPhone: "654-987-3210",
    attendingPhysician: {
      name: "Dr. Brown",
      date: new Date("2025-04-02"),
    },
    followUpNotes: 
      {
        note: "Patient is stable and ready for discharge.",
        date: new Date("2025-04-03"),
      },
    emergencyContact: {
      contactName: "Bob Adams",
      phoneNumber: "555-234-5678",
      relationship: "Brother",
    },
    levelOfConsciousness: "Confused",
    painAssessment: {
      onset: "Gradual",
      provocation: "Rest",
      quality: "Dull",
      radiation: "None",
      severity: "Mild",
      time: "Evening",
    },
    allergies: [
      {
        date: new Date("2024-08-22"),
        substance: "Shellfish",
        symptoms: "Swelling",
      },
    ],
    medications: [
      {
        date: new Date("2025-03-25"),
        medication: "Paracetamol",
        strength: "500mg",
      },
    ],
    pastMedicalHistory: "Asthma",
    vitalSignCheck: {
      heartRate: "80 bpm",
      bloodPressure: "110/70 mmHg",
      oxygenSaturation: "95%",
      temperature: "36.8°C",
      respiratoryRate: "16 breaths/min",
      gcs: "14",
      checkedBy: {
        name: "Dr. Green",
        dateTime: "2025-04-02 9:00 AM",
      },
    },
    immunizations: [
      {
        date: new Date("2023-12-10"),
        type: "Hepatitis B",
        site: "Right Arm",
      },
    ],
    nutrition: {
      hasFoodAllergies: "Yes",
      specificDiet: "None",
      mealsPerDay: "3",
      chewingOrSwallowingDifficulty: "No",
      fruitVegConsumption: "Occasionally",
      enoughWaterDaily: "Yes",
      appetiteIssues: "No",
      consumesSugaryProcessedFoods: "Yes",
    },
    chiefComplaint: "Severe headache",
    signsAndSymptoms: "Nausea, vomiting",
    caseType: "Medical",
    circulationPulse: "Weak",
    breathing: "Present",
    breathingSound: "Rhonchi",
    breathingQuality: "Labored",
    oxygen: {
      required: "Yes",
      details: [
        {
          given: "Yes",
          ipmVia: "Nasal Cannula",
          timeStart: "2025-04-02 08:00 AM",
          timeEnd: "2025-04-02 09:00 AM",
        },
      ],
    },
    adjuncts: {
      intubated: "No",
      avFistula: "No",
      colostomyBag: "No",
      paceMaker: "No",
    },
    traumaBurnAssessment: {
      wholeHeadNeck: "No",
      entireRightArm: "No",
      entireLeftArm: "No",
      entireTrunk: "No",
      groin: "No",
      entireRightLeg: "No",
      entireLeftLeg: "No",
    },
    treatmentPlan: "Administer oxygen and pain relief",
    recoveryPlan: "Monitor for changes in symptoms",
    interventions: "Administer paracetamol",
    evaluation: "Patient showing some relief",
    labResults: [],
    imagingResults: [],
    endorsements: [],
  },
  {
    name: "Emma White",
    age: 60,
    gender: "Female",
    dateOfBirth: new Date("1964-11-17"),
    weight: 75,
    height: 160,
    maritalStatus: "Widowed",
    maillingAddress: "emma@gmail.com",
    roomNumber: "C305",
    religion: "Catholic",
    workPhone: "555-999-1234",
    personalPhone: "555-888-2345",
    attendingPhysician: {
      name: "Dr. Lee",
      date: new Date("2025-04-01"),
    },
    followUpNotes:
      {
        note: "Patient needs more monitoring due to ongoing symptoms.",
        date: new Date("2025-04-02"),
      },
    emergencyContact: {
      contactName: "Michael White",
      phoneNumber: "555-333-7890",
      relationship: "Son",
    },
    levelOfConsciousness: "Pain",
    painAssessment: {
      onset: "Sudden",
      provocation: "Movement",
      quality: "Sharp",
      radiation: "To chest",
      severity: "Severe",
      time: "Night",
    },
    allergies: [],
    medications: [
      {
        date: new Date("2025-03-28"),
        medication: "Aspirin",
        strength: "325mg",
      },
    ],
    pastMedicalHistory: "Diabetes, Heart Disease",
    vitalSignCheck: {
      heartRate: "88 bpm",
      bloodPressure: "140/90 mmHg",
      oxygenSaturation: "92%",
      temperature: "38.2°C",
      respiratoryRate: "22 breaths/min",
      gcs: "12",
      checkedBy: {
        name: "Dr. Kim",
        dateTime: "2025-04-01 11:30 AM",
      },
    },
    immunizations: [],
    nutrition: {
      hasFoodAllergies: "No",
      specificDiet: "Diabetic",
      mealsPerDay: "3",
      chewingOrSwallowingDifficulty: "No",
      fruitVegConsumption: "Daily",
      enoughWaterDaily: "Yes",
      appetiteIssues: "No",
      consumesSugaryProcessedFoods: "No",
    },
    chiefComplaint: "Severe chest pain",
    signsAndSymptoms: "Sweating, dizziness",
    caseType: "Medical",
    circulationPulse: "Weak",
    breathing: "Present",
    breathingSound: "Crackles",
    breathingQuality: "Labored",
    oxygen: {
      required: "Yes",
      details: [
        {
          given: "Yes",
          ipmVia: "Face Mask",
          timeStart: "2025-04-01 12:00 PM",
          timeEnd: "2025-04-01 01:00 PM",
        },
      ],
    },
    adjuncts: {
      intubated: "No",
      avFistula: "No",
      colostomyBag: "No",
      paceMaker: "No",
    },
    traumaBurnAssessment: {
      wholeHeadNeck: "No",
      entireRightArm: "No",
      entireLeftArm: "No",
      entireTrunk: "No",
      groin: "No",
      entireRightLeg: "No",
      entireLeftLeg: "No",
    },
    treatmentPlan: "Administer oxygen and monitor vitals",
    recoveryPlan: "Discharge after stabilization",
    interventions: "Pain relief and oxygen therapy",
    evaluation: "Patient stable, continue monitoring",
    labResults: [],
    imagingResults: [],
    endorsements: [],
  },
  {
    name: "Jane Smith",
    age: 45,
    gender: "Female",
    dateOfBirth: new Date("1979-05-14"),
    weight: 68,
    height: 160,
    maritalStatus: "Married",
    maillingAddress: "jane@gmail.com",
    roomNumber: "A102",
    religion: "Christianity",
    workPhone: "123-456-7890",
    personalPhone: "098-765-4321",
    attendingPhysician: {
      name: "Dr. John Doe",
      date: new Date("2025-04-01"),
    },
    followUpNotes: 
      {
        note: "Patient is recovering well after surgery. Follow-up in 1 month.",
        date: new Date("2025-04-02"),
      },
    emergencyContact: {
      contactName: "Robert Smith",
      phoneNumber: "123-555-6789",
      relationship: "Husband",
    },
    levelOfConsciousness: "Alert",
    painAssessment: {
      onset: "Sudden",
      provocation: "Movement",
      quality: "Sharp",
      radiation: "None",
      severity: "Moderate",
      time: "Morning",
    },
    allergies: [
      {
        date: new Date("2025-03-15"),
        substance: "Peanuts",
        symptoms: "Swelling and rash",
      },
    ],
    medications: [
      {
        date: new Date("2025-04-01"),
        medication: "Ibuprofen",
        strength: "200mg",
      },
    ],
    pastMedicalHistory: "Asthma, Hypertension",
    vitalSignCheck: {
      heartRate: "85 bpm",
      bloodPressure: "120/80 mmHg",
      oxygenSaturation: "98%",
      temperature: "37.1°C",
      respiratoryRate: "16 breaths/min",
      gcs: "15",
      checkedBy: {
        name: "Nurse Emily",
        dateTime: "2025-04-02 10:00",
      },
    },
    immunizations: [
      {
        date: new Date("2024-11-10"),
        type: "Flu Vaccine",
        site: "Left Arm",
      },
    ],
    nutrition: {
      hasFoodAllergies: "Yes",
      specificDiet: "Low Salt",
      mealsPerDay: "3",
      chewingOrSwallowingDifficulty: "No",
      fruitVegConsumption: "High",
      enoughWaterDaily: "Yes",
      appetiteIssues: "No",
      consumesSugaryProcessedFoods: "Occasionally",
    },
    chiefComplaint: "Persistent headaches",
    signsAndSymptoms: "Mild fever, nausea",
    caseType: "Medical",
    circulationPulse: "Strong",
    breathing: "Present",
    breathingSound: "Clear",
    breathingQuality: "Normal",
    oxygen: {
      required: "No",
      details: [],
    },
    adjuncts: {
      intubated: "No",
      avFistula: "No",
      colostomyBag: "No",
      paceMaker: "No",
    },
    traumaBurnAssessment: {
      wholeHeadNeck: "No injury",
      entireRightArm: "No injury",
      entireLeftArm: "No injury",
      entireTrunk: "No injury",
      groin: "No injury",
      entireRightLeg: "No injury",
      entireLeftLeg: "No injury",
    },
    treatmentPlan: "Monitor pain and blood pressure, follow-up in 2 weeks.",
    recoveryPlan: "Gradual return to normal activities.",
    interventions: "Administered pain relief.",
    evaluation: "Patient improving steadily.",
    labResults: [
      {
        typeOfTest: "Blood Test",
        collectionDate: new Date("2025-04-01"),
        provider: "LabCorp",
        result: "Good"
      },
    ],
    imagingResults: [
      {
        typeOfImaging: "X-Ray",
        dateOfExam: new Date("2025-03-30"),
        provider: "Radiology Clinic",
        result: "No fractured Bone"
      },
    ],
    endorsements: [
      {
        answer: "Confirmed",
        endorsedBy: "Dr. John Doe",
        endorsedAt: "2025-04-01",
        receivedBy: "Nurse Emily",
        receivedAt: "2025-04-02",
      },
    ],
  },
  {
    name: "Tom Brown",
    age: 60,
    gender: "Female",
    dateOfBirth: new Date("1964-03-10"),
    weight: 80,
    height: 175,
    maritalStatus: "Divorced",
    maillingAddress: "tom@gmail.com",
    roomNumber: "B205",
    religion: "Buddhism",
    workPhone: "321-654-9870",
    personalPhone: "087-654-3210",
    attendingPhysician: {
      name: "Dr. Sarah Lee",
      date: new Date("2025-04-01"),
    },
    followUpNotes:
      {
        note: "Patient is stable after heart surgery. Schedule follow-up in 3 weeks.",
        date: new Date("2025-04-02"),
      },
    emergencyContact: {
      contactName: "Mary Brown",
      phoneNumber: "321-555-1234",
      relationship: "Daughter",
    },
    levelOfConsciousness: "Alert",
    painAssessment: {
      onset: "Gradual",
      provocation: "Physical exertion",
      quality: "Dull",
      radiation: "Left arm",
      severity: "Severe",
      time: "Afternoon",
    },
    allergies: [
      {
        date: new Date("2025-01-20"),
        substance: "Penicillin",
        symptoms: "Rash and swelling",
      },
    ],
    medications: [
      {
        date: new Date("2025-04-01"),
        medication: "Aspirin",
        strength: "81mg",
      },
    ],
    pastMedicalHistory: "Heart disease, Diabetes",
    vitalSignCheck: {
      heartRate: "70 bpm",
      bloodPressure: "130/85 mmHg",
      oxygenSaturation: "97%",
      temperature: "36.9°C",
      respiratoryRate: "18 breaths/min",
      gcs: "15",
      checkedBy: {
        name: "Nurse Olivia",
        dateTime: "2025-04-02 12:30",
      },
    },
    immunizations: [
      {
        date: new Date("2024-12-01"),
        type: "Pneumonia Vaccine",
        site: "Right Arm",
      },
    ],
    nutrition: {
      hasFoodAllergies: "Yes",
      specificDiet: "Low Sugar",
      mealsPerDay: "3",
      chewingOrSwallowingDifficulty: "No",
      fruitVegConsumption: "Moderate",
      enoughWaterDaily: "Yes",
      appetiteIssues: "No",
      consumesSugaryProcessedFoods: "Rarely",
    },
    chiefComplaint: "Shortness of breath",
    signsAndSymptoms: "Fatigue, dizziness",
    caseType: "Medical",
    circulationPulse: "Present",
    breathing: "Present",
    breathingSound: "Clear",
    breathingQuality: "Normal",
    oxygen: {
      required: "No",
      details: [],
    },
    adjuncts: {
      intubated: "No",
      avFistula: "No",
      colostomyBag: "No",
      paceMaker: "Yes",
    },
    traumaBurnAssessment: {
      wholeHeadNeck: "No injury",
      entireRightArm: "No injury",
      entireLeftArm: "No injury",
      entireTrunk: "No injury",
      groin: "No injury",
      entireRightLeg: "No injury",
      entireLeftLeg: "No injury",
    },
    treatmentPlan: "Administer aspirin, monitor for chest pain.",
    recoveryPlan: "Cardiac rehabilitation, follow-up in 3 weeks.",
    interventions: "Administered oxygen and pain relief.",
    evaluation: "Patient stable, discharge expected in 2 days.",
    labResults: [
      {
        typeOfTest: "ECG",
        collectionDate: new Date("2025-03-25"),
        provider: "Cardiology Center",
        result: "Normal Sinus Rhythm"
      },
    ],
    imagingResults: [
      {
        typeOfImaging: "CT Scan",
        dateOfExam: new Date("2025-03-24"),
        provider: "Imaging Services",
        result: " No Abnormalities Detected"
      },
    ],
    endorsements: [
      {
        answer: "Reviewed",
        endorsedBy: "Dr. Sarah Lee",
        endorsedAt: "2025-04-01",
        receivedBy: "Nurse Olivia",
        receivedAt: "2025-04-02",
      },
    ],
  },
  {
    name: "Alice Green",
    age: 30,
    gender: "Female",
    dateOfBirth: new Date("1994-09-20"),
    weight: 55,
    height: 170,
    maritalStatus: "Single",
    maillingAddress: "alice@gmail.com",
    roomNumber: "C307",
    religion: "Christianity",
    workPhone: "654-321-9870",
    personalPhone: "090-876-5432",
    attendingPhysician: {
      name: "Dr. Peter Adams",
      date: new Date("2025-04-01"),
    },
    followUpNotes: 
      {
        note: "Patient showing improvement post-operation. Follow-up in 1 month.",
        date: new Date("2025-04-02"),
      },
    emergencyContact: {
      contactName: "Laura Green",
      phoneNumber: "654-555-7777",
      relationship: "Mother",
    },
    levelOfConsciousness: "Alert",
    painAssessment: {
      onset: "Sudden",
      provocation: "Stress",
      quality: "Throbbing",
      radiation: "Neck",
      severity: "Mild",
      time: "Evening",
    },
    allergies: [
      {
        date: new Date("2025-03-05"),
        substance: "Shellfish",
        symptoms: "Swelling",
      },
    ],
    medications: [
      {
        date: new Date("2025-04-01"),
        medication: "Paracetamol",
        strength: "500mg",
      },
    ],
    pastMedicalHistory: "No significant medical history",
    vitalSignCheck: {
      heartRate: "78 bpm",
      bloodPressure: "110/70 mmHg",
      oxygenSaturation: "99%",
      temperature: "36.7°C",
      respiratoryRate: "16 breaths/min",
      gcs: "15",
      checkedBy: {
        name: "Nurse Amanda",
        dateTime: "2025-04-02 14:00",
      },
    },
    immunizations: [
      {
        date: new Date("2024-10-15"),
        type: "COVID-19 Booster",
        site: "Right Arm",
      },
    ],
    nutrition: {
      hasFoodAllergies: "Yes",
      specificDiet: "None",
      mealsPerDay: "3",
      chewingOrSwallowingDifficulty: "No",
      fruitVegConsumption: "High",
      enoughWaterDaily: "Yes",
      appetiteIssues: "No",
      consumesSugaryProcessedFoods: "Rarely",
    },
    chiefComplaint: "Severe stomach cramps",
    signsAndSymptoms: "Nausea, dizziness",
    caseType: "Medical",
    circulationPulse: "Strong",
    breathing: "Present",
    breathingSound: "Clear",
    breathingQuality: "Normal",
    oxygen: {
      required: "No",
      details: [],
    },
    adjuncts: {
      intubated: "No",
      avFistula: "No",
      colostomyBag: "No",
      paceMaker: "No",
    },
    traumaBurnAssessment: {
      wholeHeadNeck: "No injury",
      entireRightArm: "No injury",
      entireLeftArm: "No injury",
      entireTrunk: "No injury",
      groin: "No injury",
      entireRightLeg: "No injury",
      entireLeftLeg: "No injury",
    },
    treatmentPlan: "Administer fluids and pain relief.",
    recoveryPlan: "Monitor symptoms and follow-up in 2 weeks.",
    interventions: "Administered IV fluids and pain medication.",
    evaluation: "Patient responding well to treatment.",
    labResults: [
      {
        typeOfTest: "Urine Test",
        collectionDate: new Date("2025-04-01"),
        provider: "LabCorp",
        result: "Normal"
      },
    ],
    imagingResults: [
      {
        typeOfImaging: "Ultrasound",
        dateOfExam: new Date("2025-03-29"),
        provider: "Diagnostic Imaging",
        result: "Pregnant"
      },
    ],
    endorsements: [
      {
        answer: "Reviewed",
        endorsedBy: "Dr. Peter Adams",
        endorsedAt: "2025-04-01",
        receivedBy: "Nurse Amanda",
        receivedAt: "2025-04-02",
      },
    ],
  },
  {
    name: "Maria Garcia",
    age: 34,
    gender: "Female",
    dateOfBirth: new Date("1991-07-22"),
    weight: 70,
    height: 160,
    maritalStatus: "Single",
    maillingAddress: "Maria@gmail.com",
    roomNumber: "B202",
    religion: "Catholic",
    workPhone: "321-654-9870",
    personalPhone: "654-321-9870",
    attendingPhysician: {
      name: "Dr. Lucas Rivera",
      date: new Date("2025-03-20"),
    },
    followUpNotes: 
      {
        note: "Patient recovering well after surgery.",
        date: new Date("2025-03-25"),
      },
    emergencyContact: {
      contactName: "Carlos Garcia",
      phoneNumber: "555-678-1234",
      relationship: "Brother",
    },
    levelOfConsciousness: "Alert",
    painAssessment: {
      onset: "Gradual",
      provocation: "Sitting for long hours",
      quality: "Dull",
      radiation: "None",
      severity: "Mild",
      time: "Afternoon",
    },
    allergies: [
      {
        date: new Date("2025-02-10"),
        substance: "Peanuts",
        symptoms: "Swelling, rash",
      },
    ],
    medications: [
      {
        date: new Date("2025-03-18"),
        medication: "Acetaminophen",
        strength: "500mg",
      },
    ],
    pastMedicalHistory: "Asthma, Hypertension",
    vitalSignCheck: {
      heartRate: "76 bpm",
      bloodPressure: "125/80 mmHg",
      oxygenSaturation: "97%",
      temperature: "36.5°C",
      respiratoryRate: "18 breaths/min",
      gcs: "15",
      checkedBy: {
        name: "Nurse Sophia",
        dateTime: new Date("2025-03-20T09:00:00"),
      },
    },
    immunizations: [
      {
        date: new Date("2025-01-15"),
        type: "Hepatitis B",
        site: "Right Arm",
      },
    ],
    nutrition: {
      hasFoodAllergies: "Yes",
      specificDiet: "Low cholesterol",
      mealsPerDay: "3",
      chewingOrSwallowingDifficulty: "No",
      fruitVegConsumption: "High",
      enoughWaterDaily: "Yes",
      appetiteIssues: "No",
      consumesSugaryProcessedFoods: "Occasionally",
    },
    chiefComplaint: "Frequent headaches",
    signsAndSymptoms: "Dizziness, blurred vision",
    caseType: "Medical",
    circulationPulse: "Present",
    breathing: "Present",
    breathingSound: "Clear",
    breathingQuality: "Normal",
    oxygen: {
      required: "No",
      details: [],
    },
    adjuncts: {
      intubated: "No",
      avFistula: "No",
      colostomyBag: "No",
      paceMaker: "No",
    },
    traumaBurnAssessment: {
      wholeHeadNeck: "No burn",
      entireRightArm: "No burn",
      entireLeftArm: "No burn",
      entireTrunk: "No burn",
      groin: "No burn",
      entireRightLeg: "No burn",
      entireLeftLeg: "No burn",
    },
    treatmentPlan: "Continue headache management, monitor blood pressure",
    recoveryPlan: "Follow-up in 2 weeks",
    interventions: "Pain management, blood pressure monitoring",
    evaluation: "Headache frequency decreased",
    labResults: [
      {
        typeOfTest: "Blood Test",
        collectionDate: new Date("2025-03-10"),
        provider: "LabTech Emily",
        result: "Good"
      },
    ],
    imagingResults: [
      {
        typeOfImaging: "CT Scan",
        dateOfExam: new Date("2025-03-12"),
        provider: "Dr. Nathan Collins",
        result: "Good good"
      },
    ],
    endorsements: [
      {
        answer: "Patient stable and under control",
        endorsedBy: "Dr. Lucas Rivera",
        endorsedAt: new Date("2025-03-20T10:00:00"),
        receivedBy: "Dr. Amelia Foster",
        receivedAt: new Date("2025-03-20T10:30:00"),
      },
    ],
  },
  {
    name: "James Thompson",
    age: 56,
    gender: "Male",
    dateOfBirth: new Date("1969-11-30"),
    weight: 95,
    height: 180,
    maritalStatus: "Married",
    maillingAddress: "James@gmail.com",
    roomNumber: "C301",
    religion: "Protestant",
    workPhone: "987-321-6540",
    personalPhone: "321-987-6543",
    attendingPhysician: {
      name: "Dr. Susan Lee",
      date: new Date("2025-03-18"),
    },
    followUpNotes:
      {
        note: "Patient is showing improvement, no new symptoms.",
        date: new Date("2025-03-21"),
      },
    emergencyContact: {
      contactName: "Laura Thompson",
      phoneNumber: "555-234-5678",
      relationship: "Wife",
    },
    levelOfConsciousness: "Alert",
    painAssessment: {
      onset: "Sudden",
      provocation: "Heavy lifting",
      quality: "Sharp",
      radiation: "Lower back",
      severity: "Severe",
      time: "Morning",
    },
    allergies: [
      {
        date: new Date("2025-01-10"),
        substance: "Shellfish",
        symptoms: "Hives, swelling",
      },
    ],
    medications: [
      {
        date: new Date("2025-03-16"),
        medication: "Lisinopril",
        strength: "10mg",
      },
    ],
    pastMedicalHistory: "Chronic back pain, Type 2 Diabetes",
    vitalSignCheck: {
      heartRate: "80 bpm",
      bloodPressure: "145/90 mmHg",
      oxygenSaturation: "96%",
      temperature: "37°C",
      respiratoryRate: "18 breaths/min",
      gcs: "15",
      checkedBy: {
        name: "Nurse Chloe",
        dateTime: new Date("2025-03-18T10:30:00"),
      },
    },
    immunizations: [
      {
        date: new Date("2025-02-05"),
        type: "Pneumococcal Vaccine",
        site: "Left Arm",
      },
    ],
    nutrition: {
      hasFoodAllergies: "Yes",
      specificDiet: "Low carb, high fiber",
      mealsPerDay: "3",
      chewingOrSwallowingDifficulty: "No",
      fruitVegConsumption: "Moderate",
      enoughWaterDaily: "Yes",
      appetiteIssues: "No",
      consumesSugaryProcessedFoods: "Rarely",
    },
    chiefComplaint: "Severe back pain",
    signsAndSymptoms: "Limited movement, muscle spasms",
    caseType: "Medical",
    circulationPulse: "Present",
    breathing: "Present",
    breathingSound: "Clear",
    breathingQuality: "Normal",
    oxygen: {
      required: "No",
      details: [],
    },
    adjuncts: {
      intubated: "No",
      avFistula: "No",
      colostomyBag: "No",
      paceMaker: "No",
    },
    traumaBurnAssessment: {
      wholeHeadNeck: "No burn",
      entireRightArm: "No burn",
      entireLeftArm: "No burn",
      entireTrunk: "No burn",
      groin: "No burn",
      entireRightLeg: "No burn",
      entireLeftLeg: "No burn",
    },
    treatmentPlan: "Pain management, physical therapy referral",
    recoveryPlan: "Re-evaluate in 2 weeks",
    interventions: "Pain relief, mobility exercises",
    evaluation: "Patient reported moderate improvement",
    labResults: [
      {
        typeOfTest: "Blood Sugar Test",
        collectionDate: new Date("2025-03-15"),
        provider: "LabTech Olivia",
        result: "Normal"
      },
    ],
    imagingResults: [
      {
        typeOfImaging: "MRI",
        dateOfExam: new Date("2025-03-14"),
        provider: "Dr. Emily Clark",
         result: "Good"
      },
    ],
    endorsements: [
      {
        answer: "Patient stable, no changes",
        endorsedBy: "Dr. Susan Lee",
        endorsedAt: new Date("2025-03-18T11:00:00"),
        receivedBy: "Dr. Richard Brown",
        receivedAt: new Date("2025-03-18T11:30:00"),
      },
    ],
  },
];
